version: "3.7"

services:
  gateway:
    build: ./packages/gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - backend

  users_service:
    build: ./packages/users_service
    restart: always
    hostname: users
    env_file:
      - .env
    ports:
      - "8001:8001"
    networks:
      - backend

  auth_service:
    build: ./packages/auth_service
    restart: always
    hostname: auth
    env_file:
      - .env
    ports:
      - "8002:8002"
    networks:
      - backend

  tasks_service:
    build: ./packages/tasks_service
    restart: always
    hostname: tasks
    env_file:
      - .env
    ports:
      - "8003:8003"
    networks:
      - backend

  tasking_frontend:
    build: ./packages/tasking_frontend
    restart: always
    hostname: tasks
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - frontend

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - "./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro"
    ports:
      - 27017:27017
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    name: infrastructure
